import { Injectable, Logger } from '@nestjs/common';

/**
 * Represents an alert generated by the system.
 */
export interface Alert {
  type: string;
  message: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  details?: any;
  timestamp: Date;
}

@Injectable()
export class AlertingService {
  private readonly logger = new Logger(AlertingService.name);
  private alerts: Alert[] = [];
  private readonly maxAlerts = 1000;

/**
   * Sends a new alert, adds a timestamp, stores it, and triggers external notifications.
   * @param alert The alert details (timestamp will be set automatically)
   */
  async sendAlert(alert: Omit<Alert, 'timestamp'>) {
    const fullAlert: Alert = {
      ...alert,
      timestamp: new Date(),
    };

    this.alerts.push(fullAlert);
    if (this.alerts.length > this.maxAlerts) {
      this.alerts = this.alerts.slice(-this.maxAlerts);
    }

    // Log the alert
    this.logger.warn(`ALERT [${alert.severity}]: ${alert.message}`, alert.details);

    // Here you would integrate with your preferred alerting system
    // Examples: Slack, Discord, Email, PagerDuty, etc.
    await this.sendToExternalServices(fullAlert);
  }

  private async sendToExternalServices(alert: Alert) {
    // --- EMAIL NOTIFICATION (Nodemailer) ---
    // Configure SMTP credentials in your environment variables
    if ((alert.severity === 'CRITICAL' || alert.severity === 'HIGH') && process.env.ALERT_EMAIL_TO && process.env.SMTP_HOST) {
      try {
        const nodemailer = require('nodemailer');
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: Number(process.env.SMTP_PORT) || 587,
          secure: process.env.SMTP_SECURE === 'true',
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });
        await transporter.sendMail({
          from: process.env.ALERT_EMAIL_FROM || process.env.SMTP_USER,
          to: process.env.ALERT_EMAIL_TO,
          subject: `[ALERT] ${alert.severity} - ${alert.type}`,
          text: `${alert.message}\nDetails: ${JSON.stringify(alert.details, null, 2)}`,
        });
        this.logger.log('Low stock alert email sent');
      } catch (error) {
        this.logger.error('Failed to send alert email', error);
      }
    }

    // --- SMS NOTIFICATION (Twilio) ---
    // Configure Twilio credentials in your environment variables
    if ((alert.severity === 'CRITICAL' || alert.severity === 'HIGH') && process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN && process.env.TWILIO_FROM && process.env.TWILIO_TO) {
      try {
        const twilio = require('twilio');
        const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);
        await client.messages.create({
          body: `[ALERT] ${alert.severity} - ${alert.message}`,
          from: process.env.TWILIO_FROM,
          to: process.env.TWILIO_TO,
        });
        this.logger.log('Low stock alert SMS sent');
      } catch (error) {
        this.logger.error('Failed to send alert SMS', error);
      }
    }

    // --- Add other integrations as needed (e.g., Slack, Discord) ---
  
    // Example implementations - uncomment and configure as needed
    
    // Slack webhook example
    // if (process.env.SLACK_WEBHOOK_URL) {
    //   try {
    //     await fetch(process.env.SLACK_WEBHOOK_URL, {
    //       method: 'POST',
    //       headers: { 'Content-Type': 'application/json' },
    //       body: JSON.stringify({
    //         text: `🚨 ${alert.severity} Alert: ${alert.message}`,
    //         attachments: [{
    //           color: this.getColorForSeverity(alert.severity),
    //           fields: Object.entries(alert.details || {}).map(([key, value]) => ({
    //             title: key,
    //             value: String(value),
    //             short: true,
    //           })),
    //         }],
    //       }),
    //     });
    //   } catch (error) {
    //     this.logger.error('Failed to send Slack alert', error);
    //   }
    // }

    // Email example (using nodemailer)
    // if (alert.severity === 'CRITICAL' || alert.severity === 'HIGH') {
    //   // Send email for high severity alerts
    // }

    // Discord webhook example
    // if (process.env.DISCORD_WEBHOOK_URL) {
    //   // Send to Discord
    // }
  }

  private getColorForSeverity(severity: string): string {
    switch (severity) {
      case 'CRITICAL': return '#FF0000';
      case 'HIGH': return '#FF6600';
      case 'MEDIUM': return '#FFAA00';
      case 'LOW': return '#FFDD00';
      default: return '#808080';
    }
  }

/**
   * Returns alerts from the last N minutes.
   * @param minutes How far back to look (default: 60)
   */
  getRecentAlerts(minutes = 60): Alert[] {
    const cutoff = new Date(Date.now() - minutes * 60 * 1000);
    return this.alerts.filter(a => a.timestamp >= cutoff);
  }

/**
   * Returns all stored alerts.
   */
  getAllAlerts(): Alert[] {
    return [...this.alerts];
  }
}
